### Name len < 3
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Yo",
  "number": "040-987654"
}

### Number is missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Taikuri Luttinen",
  "number": ""
}

### Number in wrong format 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Luikuri Tattinen",
  "number": "1-1234567"
}

### Too few numbers
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Luikuri Tattinen",
  "number": "12-34567"
}

### Too few numbers 2
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Luikuri Tattinen",
  "number": "123-4567"
}

### Malformatted id DELETE
DELETE http://localhost:3001/api/persons/1

### Malformatted id GET
GET http://localhost:3001/api/persons/1